// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much the agent may do without asking. Stored per app, not per run.
 */
export type AgentAutonomy = "read_only" | "ask_on_write" | "full";
