// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentChatRequest = { connectionId: string, 
/**
 * Stable per chat surface, so a tab keeps its memory between messages.
 */
chatId: string, 
/**
 * Minted by the caller so it can filter events before the reply lands.
 */
runId: string, prompt: string, 
/**
 * What the user was looking at: the editor's statement, the open table.
 */
context: string | null, 
/**
 * False for the editor's one-shot generate, which must not read the database.
 */
useTools: boolean, };
