// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentArtifact } from "./AgentArtifact";
import type { AgentStop } from "./AgentStop";
import type { AgentUsage } from "./AgentUsage";
import type { ToolCallRecord } from "./ToolCallRecord";

/**
 * The finished turn. Also what `ai_generate` returns after collapsing to one step.
 */
export type AgentTurn = { runId: string, model: string, 
/**
 * The assistant's prose, as markdown.
 */
text: string, 
/**
 * Last runnable statement the turn produced, for "open in editor".
 */
sql: string | null, toolCalls: Array<ToolCallRecord>, artifacts: Array<AgentArtifact>, usage: AgentUsage, stop: AgentStop, };
