// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentArtifact } from "./AgentArtifact";
import type { AgentTurn } from "./AgentTurn";
import type { AgentUsage } from "./AgentUsage";
import type { PermissionRequest } from "./PermissionRequest";
import type { ToolCallRecord } from "./ToolCallRecord";

export type AgentEvent = { "type": "started", runId: string, chatId: string, model: string, } | { "type": "thinking", runId: string, delta: string, } | { "type": "text", runId: string, delta: string, } | { "type": "step", runId: string, step: number, } | { "type": "tool_started", runId: string, call: ToolCallRecord, } | { "type": "tool_finished", runId: string, call: ToolCallRecord, } | { "type": "artifact", runId: string, artifact: AgentArtifact, } | { "type": "permission", runId: string, request: PermissionRequest, } | { "type": "usage", runId: string, usage: AgentUsage, } | { "type": "finished", runId: string, turn: AgentTurn, } | { "type": "failed", runId: string, message: string, };
