// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A prompt pack the model loads by name instead of carrying in every request.
 */
export type AgentSkill = { id: string, name: string, 
/**
 * The one line that sits in context so the model knows when to load the rest.
 */
description: string, };
