// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryOutcome } from "./QueryOutcome";
import type { UiBlock } from "./UiBlock";
import type { UiGraphEdge } from "./UiGraphEdge";
import type { UiGraphNode } from "./UiGraphNode";
import type { WidgetKind } from "./WidgetKind";

/**
 * A view the agent asked the UI to draw. Every artifact is a query plus a way to
 * render it, so the client can re-run it and switch the rendering on its own.
 */
export type AgentArtifact = { "kind": "chart", id: string, title: string, chart: WidgetKind, xLabel: string | null, yLabel: string | null, sql: string, outcome: QueryOutcome, } | { "kind": "table", id: string, title: string, sql: string, outcome: QueryOutcome, } | { "kind": "graph", id: string, title: string, sql: string, 
/**
 * Built server-side (foreign keys, for engines with no graph query
 * language). Empty means: derive them from `outcome` on the client,
 * which already knows how to read a graph engine's result shape.
 */
nodes: Array<UiGraphNode>, edges: Array<UiGraphEdge>, outcome: QueryOutcome | null, } | { "kind": "ui", id: string, title: string, blocks: Array<UiBlock>, };
