// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAutonomy } from "./AgentAutonomy";
import type { AiProvider } from "./AiProvider";

export type AiSettings = { provider: AiProvider, model: string, 
/**
 * Override for self-hosted / proxy endpoints (Ollama defaults to http://127.0.0.1:11434).
 */
baseUrl: string | null, 
/**
 * Never contains the key itself; the key is sealed separately in the store.
 */
hasApiKey: boolean, 
/**
 * How far the assistant may act on its own before asking. Defaulted so
 * settings written before the agent existed still load.
 */
autonomy: AgentAutonomy, };
