// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupFormat = "custom" | "plain" | "directory" | "tar" | "archive" | "file";
