// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupFormat } from "./BackupFormat";
import type { BackupMethod } from "./BackupMethod";
import type { NativeToolStatus } from "./NativeToolStatus";

export type BackupSupport = { 
/**
 * None: this engine has no backup path in the app.
 */
method: BackupMethod | null, 
/**
 * Formats a backup can be written in; the first is the default.
 */
formats: Array<BackupFormat>, 
/**
 * The tools this method uses, found or not.
 */
tools: Array<NativeToolStatus>, 
/**
 * True when the connection must be disconnected before a restore
 * (file engines: the file is replaced underneath the session).
 */
restoreNeedsDisconnect: boolean, 
/**
 * True when the connection must be disconnected before a backup (DuckDB
 * holds an exclusive lock on its file while open).
 */
backupNeedsDisconnect: boolean, 
/**
 * Why there is no method, or a caveat about the one there is.
 */
note: string | null, };
