// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupReport = { path: string, 
/**
 * Size of the backup written or read, when it is a single file.
 */
bytes: number | null, elapsedMs: number, 
/**
 * The program that did the work ("pg_dump", "VACUUM INTO", …).
 */
tool: string, 
/**
 * True when the user stopped the run; a partial backup file is removed.
 */
cancelled: boolean, };
