// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupOptions } from "./BackupOptions";

export type BackupRequest = { connectionId: string, 
/**
 * Minted by the caller so it can filter events and cancel.
 */
runId: string, 
/**
 * Absolute path picked in the native save dialog.
 */
path: string, options: BackupOptions, };
