// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupFormat } from "./BackupFormat";

export type BackupOptions = { format: BackupFormat, schemaOnly: boolean, dataOnly: boolean, 
/**
 * Postgres: limit to these schemas.
 */
schemas: Array<string>, 
/**
 * Postgres / MySQL: limit to these tables.
 */
tables: Array<string>, 
/**
 * Postgres: drop objects before recreating them (plain dump / pg_restore).
 */
clean: boolean, 
/**
 * Postgres: skip ALTER OWNER, so a restore works as a different role.
 */
noOwner: boolean, 
/**
 * MySQL: include stored procedures and functions.
 */
routines: boolean, 
/**
 * MySQL: include triggers.
 */
triggers: boolean, 
/**
 * MySQL dump: one consistent snapshot (InnoDB). Postgres / MySQL restore:
 * all-or-nothing.
 */
singleTransaction: boolean, 
/**
 * MongoDB: gzip the archive.
 */
gzip: boolean, 
/**
 * MongoDB restore: drop each collection before restoring it.
 */
drop: boolean, };
