// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Capabilities = { 
/**
 * Accepts SQL text in `execute`.
 */
sql: boolean, 
/**
 * Groups collections under named schemas / databases / keyspaces.
 */
namespaces: boolean, 
/**
 * Has a stable column set per collection (false for schemaless documents).
 */
fixedColumns: boolean, 
/**
 * Supports offset paging in `fetch_page`.
 */
paging: boolean, 
/**
 * Can report an approximate row / key count cheaply.
 */
rowEstimate: boolean, 
/**
 * Distinguishes tables from views.
 */
views: boolean, 
/**
 * `BEGIN … COMMIT` wraps multi-statement scripts (imports, pending changes).
 */
transactions: boolean, 
/**
 * `row_estimate` is an exact count, not a statistics guess.
 */
exactEstimate: boolean, 
/**
 * `columns` describes the object it is asked about. False when it returns a
 * fixed pseudo-schema that is the same for every object (an S3 bucket's
 * key/size/etag, a Kafka topic's partition/offset/value, a Pinecone index's
 * id/values/metadata): listing those as an object's "fields" would show the
 * same uninformative rows everywhere.
 */
describesFields: boolean, };
