// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnChange } from "./ColumnChange";
import type { ColumnInfo } from "./ColumnInfo";
import type { DiffStatus } from "./DiffStatus";

export type ColumnDiff = { name: string, status: DiffStatus, left: ColumnInfo | null, right: ColumnInfo | null, changes: Array<ColumnChange>, };
