// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompareDirection } from "./CompareDirection";
import type { TableSide } from "./TableSide";

export type CompareTableDataRequest = { left: TableSide, right: TableSide, 
/**
 * Columns rows are matched by; empty = the primary key.
 */
keyColumns: Array<string>, 
/**
 * Rows read per side; None = the service default (100k).
 */
maxRows: number | null, direction: CompareDirection, 
/**
 * Also write the INSERT / UPDATE / DELETE script for the target.
 */
includeScript: boolean, };
