// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine";
import type { Environment } from "./Environment";
import type { SshTunnel } from "./SshTunnel";
import type { SslMode } from "./SslMode";

export type ConnectionSummary = { id: string, name: string, engine: Engine, environment: Environment, readOnly: boolean, host: string | null, port: number | null, database: string | null, username: string | null, filePath: string | null, sslMode: SslMode, hasSecret: boolean, ssh: SshTunnel, 
/**
 * True when an SSH password / key passphrase is sealed in the store.
 */
hasSshSecret: boolean, createdAt: string, updatedAt: string, };
