// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Engine } from "./Engine";
import type { Environment } from "./Environment";
import type { SshTunnel } from "./SshTunnel";
import type { SslMode } from "./SslMode";

export type ConnectionInput = { name: string, engine: Engine, environment: Environment, readOnly: boolean, host: string | null, port: number | null, database: string | null, username: string | null, password: string | null, filePath: string | null, sslMode: SslMode, ssh: SshTunnel, 
/**
 * Write-only like `password`: the SSH password or the key's passphrase.
 */
sshSecret: string | null, };
