// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnInfo } from "./ColumnInfo";
import type { TableRef } from "./TableRef";

export type CreateTemplateRequest = { connectionId: string, table: TableRef, 
/**
 * Columns the user described in the New-table dialog.
 */
columns: Array<ColumnInfo>, };
