// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnInfo } from "./ColumnInfo";
import type { CompareDirection } from "./CompareDirection";
import type { RowDiff } from "./RowDiff";

export type DataCompare = { direction: CompareDirection, 
/**
 * Columns present on both sides, in the left table's order.
 */
columns: Array<ColumnInfo>, keyColumns: Array<string>, leftOnlyColumns: Array<string>, rightOnlyColumns: Array<string>, rows: Array<RowDiff>, rowsTruncated: boolean, onlyLeft: number, onlyRight: number, different: number, identical: number, leftRows: number, rightRows: number, leftCapped: boolean, rightCapped: boolean, 
/**
 * INSERT / UPDATE / DELETE statements that make the target match the
 * source. None when not asked for or the target speaks no SQL.
 */
script: string | null, notes: Array<string>, };
