// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DetectToolsRequest = { 
/**
 * None lists every tool (Settings → Advanced).
 */
connectionId: string | null, };
