// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DownloadObjectRequest = { connectionId: string, bucket: string, key: string, path: string, };
