// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineKind } from "./EngineKind";
import type { Family } from "./Family";
import type { FormKind } from "./FormKind";

export type EngineFacts = { kind: EngineKind, form: FormKind, defaultPort: number | null, 
/**
 * Adapter that speaks to it: what the object explorer and tool tabs key on.
 */
family: Family, };
