// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecuteQueryRequest = { connectionId: string, sql: string, confirmDestructive: boolean, maxRows: number | null, schema: string | null, };
