// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExecuteQueryRequest = { connectionId: string, sql: string, confirmDestructive: boolean, 
/**
 * None = "No limit" in the editor; otherwise clamped by the block.
 */
maxRows: number | null, 
/**
 * Schema / keyspace the editor's picker is on, applied for this run only.
 */
schema: string | null, };
