// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetValue } from "./FacetValue";

export type FacetCounts = { field: string, values: Array<FacetValue>, };
