// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { ObjectKind } from "./ObjectKind";
import type { Tool } from "./Tool";

export type FamilyProfile = { capabilities: Capabilities, objectKinds: Array<ObjectKind>, tools: Array<Tool>, };
