// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffStatus } from "./DiffStatus";
import type { ForeignKey } from "./ForeignKey";

export type ForeignKeyDiff = { status: DiffStatus, left: ForeignKey | null, right: ForeignKey | null, };
