// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NativeTool = "pg_dump" | "pg_restore" | "psql" | "mysqldump" | "mysql" | "mongodump" | "mongorestore";
