// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NativeTool } from "./NativeTool";

export type NativeToolStatus = { tool: NativeTool, 
/**
 * Resolved executable, when found.
 */
path: string | null, 
/**
 * First line of `--version`, when it answered.
 */
version: string | null, 
/**
 * True when the path came from Settings → Advanced rather than PATH.
 */
overridden: boolean, 
/**
 * What to install, for the "not found" message.
 */
package: string, };
