// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectKind } from "./ObjectKind";

export type ObjectsRequest = { connectionId: string, kind: ObjectKind, parent: string | null, };
