// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectRef } from "./ObjectRef";

export type ObjectSummary = { reference: ObjectRef, 
/**
 * Short secondary text: signature, owner, row count, state, TTL…
 */
detail: string | null, 
/**
 * Engine-specific subtype shown as a chip: `enum`, `btree`, `gsi`, `idle`, `leader`…
 */
badge: string | null, };
