// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeLanguage } from "./CodeLanguage";
import type { ColumnInfo } from "./ColumnInfo";
import type { ObjectAction } from "./ObjectAction";
import type { ObjectProperty } from "./ObjectProperty";
import type { ObjectRef } from "./ObjectRef";
import type { ObjectSummary } from "./ObjectSummary";
import type { ResultSet } from "./ResultSet";

export type ObjectDetail = { reference: ObjectRef, definition: string | null, language: CodeLanguage, properties: Array<ObjectProperty>, columns: Array<ColumnInfo>, rows: ResultSet | null, children: Array<ObjectSummary>, actions: Array<ObjectAction>, };
