// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatementIntent } from "./StatementIntent";

/**
 * A tool call waiting on the user before it may run.
 */
export type PermissionRequest = { callId: string, tool: string, 
/**
 * One-line description of what the call would do.
 */
title: string, 
/**
 * The statement itself when the tool runs one, so the user reads it before deciding.
 */
statement: string | null, 
/**
 * Per-statement previews from the classifier, already annotated with why they are destructive.
 */
statements: Array<string>, intent: StatementIntent, reason: string, };
