// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user decided about one pending tool call.
 */
export type PermissionDecision = "allow" | "allow_for_run" | "deny";
