// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanNode } from "./PlanNode";

export type PlanReport = { plan: string, explanation: string | null, 
/**
 * The same plan as a tree, for engines whose adapter can read a
 * structured EXPLAIN (Postgres, MySQL/MariaDB, SQLite). None elsewhere:
 * the UI then shows only the text.
 */
planTree: PlanNode | null, };
