// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlanNode = { label: string, detail: string | null, cost: number | null, rows: number | null, actualMs: number | null, children: Array<PlanNode>, };
