// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatementResult } from "./StatementResult";

export type QueryOutcome = { statements: Array<StatementResult>, totalRows: number | null, elapsedMs: number, };
