// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeQueryRequest } from "./RangeQueryRequest";

export type RangeQueryCommand = { connectionId: string, request: RangeQueryRequest, };
