// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RangeQueryRequest = { query: string, start: number, end: number, stepSeconds: number, };
