// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Series } from "./Series";

export type RangeResult = { series: Array<Series>, warnings: Array<string>, };
