// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupOptions } from "./BackupOptions";

export type RestoreRequest = { connectionId: string, runId: string, 
/**
 * Absolute path picked in the native open dialog.
 */
path: string, options: BackupOptions, 
/**
 * The user's explicit yes to overwriting the target (guard step 11).
 */
confirmDestructive: boolean, };
