// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RowStatus } from "./RowStatus";
import type { Value } from "./Value";

export type RowDiff = { status: RowStatus, key: Array<Value>, left: Array<Value> | null, right: Array<Value> | null, 
/**
 * Columns whose values differ (Different rows only).
 */
changed: Array<string>, };
