// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SaveSqlFileRequest = { 
/**
 * Chosen in the OS save dialog; `.sql` is forced on if it is missing.
 */
path: string, sql: string, };
