// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompareDirection } from "./CompareDirection";
import type { Engine } from "./Engine";
import type { TableDiff } from "./TableDiff";

export type SchemaDiff = { direction: CompareDirection, leftEngine: Engine, rightEngine: Engine, tables: Array<TableDiff>, script: string, 
/**
 * Caveats worth reading before running the script (cross-engine compare…).
 */
notes: Array<string>, };
