// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SchemaSide = { connectionId: string, 
/**
 * A schema name as the catalog lists it; None takes the first one.
 */
schema: string | null, };
