// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompareDirection } from "./CompareDirection";
import type { SchemaSide } from "./SchemaSide";

export type SchemaDiffRequest = { left: SchemaSide, right: SchemaSide, direction: CompareDirection, };
