// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchRequest } from "./SearchRequest";

export type SearchCommand = { connectionId: string, request: SearchRequest, };
