// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchRequest = { index: string, query: string, filter: string | null, facets: Array<string>, sort: Array<string>, highlight: boolean, limit: number, offset: number, };
