// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FacetCounts } from "./FacetCounts";
import type { ResultSet } from "./ResultSet";

export type SearchResult = { hits: ResultSet, total: number | null, facets: Array<FacetCounts>, tookMs: number | null, };
