// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ObjectProperty } from "./ObjectProperty";

export type Series = { 
/**
 * Label set / tag set identifying the series, as `key=value` text.
 */
name: string, labels: Array<ObjectProperty>, 
/**
 * `[timestamp_seconds, value]` pairs, ascending.
 */
points: Array<[number, number]>, };
