// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatGroup } from "./StatGroup";

export type ServerStats = { groups: Array<StatGroup>, 
/**
 * ISO-8601 timestamp the figures were read at.
 */
collectedAt: string, };
