// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Capabilities } from "./Capabilities";
import type { Engine } from "./Engine";
import type { ObjectKind } from "./ObjectKind";
import type { Tool } from "./Tool";

export type SessionInfo = { engine: Engine, capabilities: Capabilities, objectKinds: Array<ObjectKind>, tools: Array<Tool>, serverVersion: string | null, 
/**
 * Database this session is attached to (Postgres) or the file (SQLite).
 */
database: string | null, 
/**
 * Every database the server exposes, for the sidebar switcher.
 */
databases: Array<string>, };
