// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAuth } from "./SshAuth";

export type SshTunnel = { enabled: boolean, host: string | null, port: number, user: string | null, auth: SshAuth, 
/**
 * Private key file on this machine (PrivateKey auth). The key itself is never copied.
 */
keyPath: string | null, 
/**
 * Pinned server key fingerprint (`SHA256:…`). None = pin on the next connect.
 */
hostKey: string | null, };
