// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stat = { label: string, value: string, unit: string | null, hint: string | null, numeric: number | null, };
