// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StatementIntent } from "./StatementIntent";

export type StatementSpan = { start: number, end: number, intent: StatementIntent, };
