// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stat } from "./Stat";

export type StatGroup = { title: string, stats: Array<Stat>, };
