// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnDiff } from "./ColumnDiff";
import type { DiffStatus } from "./DiffStatus";
import type { ForeignKeyDiff } from "./ForeignKeyDiff";
import type { TableRef } from "./TableRef";

export type TableDiff = { name: string, status: DiffStatus, left: TableRef | null, right: TableRef | null, columns: Array<ColumnDiff>, foreignKeys: Array<ForeignKeyDiff>, };
