// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Tool = "stats" | "key_browser" | "erd" | "vector_search" | "search_playground" | "metrics_explorer" | "message_viewer" | "pipeline_builder" | "ledger_history" | "graph_view" | "pub_sub" | "xml_viewer";
