// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToolStatus } from "./ToolStatus";

/**
 * One tool invocation, as the timeline renders it.
 */
export type ToolCallRecord = { id: string, tool: string, 
/**
 * Human summary of the call ("List tables in public").
 */
title: string, 
/**
 * Pretty-printed arguments, shown when the row is expanded.
 */
input: string, status: ToolStatus, 
/**
 * Result headline ("24 tables", "3 rows in 12 ms"). None while running.
 */
summary: string | null, error: string | null, elapsedMs: number, };
