// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryOutcome } from "./QueryOutcome";
import type { UiGraphEdge } from "./UiGraphEdge";
import type { UiGraphNode } from "./UiGraphNode";
import type { UiStat } from "./UiStat";
import type { UiTone } from "./UiTone";
import type { WidgetKind } from "./WidgetKind";

export type UiBlock = { "block": "heading", text: string, } | { "block": "text", markdown: string, } | { "block": "stats", stats: Array<UiStat>, } | { "block": "chart", title: string, chart: WidgetKind, xLabel: string | null, yLabel: string | null, sql: string, outcome: QueryOutcome, } | { "block": "table", title: string, sql: string, outcome: QueryOutcome, } | { "block": "graph", title: string, nodes: Array<UiGraphNode>, edges: Array<UiGraphEdge>, } | { "block": "facts", title: string, rows: Array<UiStat>, } | { "block": "callout", tone: UiTone, title: string, body: string, } | { "block": "divider" };
