// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A node in a rendered graph.
 */
export type UiGraphNode = { id: string, 
/**
 * The type name, which decides the colour: a table, a label, a class.
 */
label: string, 
/**
 * What is written on the node.
 */
caption: string, };
