// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One figure in a KPI row.
 */
export type UiStat = { label: string, value: string, 
/**
 * Small print under the figure — the denominator, the period, the caveat.
 */
hint: string | null, 
/**
 * Percentage change, when the agent computed one. Drives the up/down tint.
 */
trend: number | null, };
