// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateProgress = { downloaded: number, 
/**
 * None when the server does not send a content length.
 */
total: number | null, 
/**
 * The download finished; installation follows, then a restart.
 */
done: boolean, };
