// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateStatus = { 
/**
 * Version this binary was built as.
 */
current: string, 
/**
 * Newer version offered by the release feed, when there is one.
 */
available: string | null, 
/**
 * Release notes for that version, as published.
 */
notes: string | null, 
/**
 * Publication date, as published (RFC 3339).
 */
published: string | null, };
