// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type VectorSearchRequest = { collection: string, vector: Array<number>, 
/**
 * Named vector / field to search (engines with several per point).
 */
vectorName: string | null, topK: number, filter: JsonValue | null, includeVectors: boolean, };
