// SOT: bindings-generator, ts-rs-export, bindings-index
// WHAT:  Regenerates src/lib/bindings from the Rust `#[ts(export)]` types.
// WHY:   TS types are derived from Rust, never hand-written twice.
// HOW:   Runs the `export_bindings` test with TS_RS_EXPORT_DIR set, then writes
//        an index.ts that re-exports every generated file.
// WHERE: src-tauri/src/lib.rs (export_bindings test)
import { execSync } from "node:child_process";
import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;
const outDir = join(root, "src/lib/bindings");
mkdirSync(outDir, { recursive: true });

// Both generators live in the same test binary; `export_` matches each.
execSync("cargo test --lib export_", {
  cwd: join(root, "src-tauri"),
  stdio: "inherit",
  env: { ...process.env, TS_RS_EXPORT_DIR: outDir, TS_RS_LARGE_INT: "number" },
});

const files = readdirSync(outDir)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts" && !f.endsWith(".gen.ts"))
  .sort();
const lines = [
  "// SOT: bindings-index (generated by scripts/bindings.mjs — do not edit by hand)",
  ...files.map((f) => `export type * from "./${f.replace(/\.ts$/, "")}";`),
  "",
];
writeFileSync(join(outDir, "index.ts"), lines.join("\n"));
console.log(`bindings: ${files.length} type file(s) exported`);
